### ISSUE TITLE
IE 11 scroller does not work properly

### ISSUE THREAD

**Issue by lst2** [btecu/ember-select#11] opened 2017-06-21 01:07 UTC
I realized that it does not support IE 11.

Click on a select, click on the scroll (arrows or scrollbar); then it's like if you're clicking outside of the select. Thus, results get undisplayed and unselected.

It quite a bit hard to debug since the select add / remove results from the DOM on an outside click.

Any clue?!

**Comment by btecu** [comment] 2017-06-21 11:52
Can you create a repo demonstrating the issue?

**Comment by btecu** [comment] 2017-06-21 14:13
I have this addon working in an project that supports IE10+ so it should work.

**Comment by lst2** [comment] 2017-06-22 03:06
Ok I will create an empty repo with your addon (great by the way!)

**Comment by lst2** [comment] 2017-06-25 03:52
IE: 11.0.14 (update version: 11.0.33)
Windows: 10

ember-cli: 2.13.1
ember-select: 0.3.0
ember-babel: 6.4.1

Here's the repo, https://bitbucket.org/thomas_leperou/x-select/overview
Living on that address, http://151.80.56.43:4201

**Comment by btecu** [comment] 2017-06-25 13:14
The documentation might be lacking, the issue is that the component adheres strictly to DDAU (data down actions up) and therefore it never mutates any values.
Therefore, you want to pass an array `values` (because you enable multiple selections) and an action (`onSelect`) that adds the selected value to the array. Also, you might also want to pass `onRemove` and `onCreate` actions.

**Comment by btecu** [comment] 2017-06-25 13:23
Here is an example:
https://bitbucket.org/Bujo/x-select/commits/977c24af468bde36cc46fcf042d5dfb707eab079

Note that `openOnFocus` is not required, it was just a preference.

**Comment by lst2** [comment] 2017-06-25 13:26
Arh, I missed something somewhere :thinking: 

I will check your exemple.

I'd like to improve my select, with a first option as "There is n results - select all". I use only collections from the datastore.

**Comment by btecu** [comment] 2017-06-25 13:37
You could insert a new record at the top of your collection with that text.
Once `onSelect` is called you can check if the record selected is the one you added and instead of adding it to `values`, you can add your entire collection.

**Comment by lst2** [comment] 2017-06-25 13:38
Using your fork, I keep getting the issue: on click on scroller or arrows, the trigger goes off.

Like if the click affects another node div while it should do to the main node scroller.

**Comment by lst2** [comment] 2017-06-25 13:43
Does make sense to add a property like `beforeModel` (this exemple be confusion compare to the beforeModel route). Then associate another action to that row.

**Comment by btecu** [comment] 2017-06-25 14:16
Before my commit it wouldn't select anything but I see the scroll issue.
The problem is that IE unlike other browsers triggers a blur event when you click on the scroll bar however you can still scroll if you're using a mouse with whell.

I'm not sure this can be easily fixed without significant hacks.

**Closed** 2017-08-01 15:08 UTC
